<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Deck_Tests.fs" />
        <Compile Include="GameState_Tests.fs" />
        <Compile Include="Player_Tests.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Casino.Core\Casino.Core.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="FsUnit.xUnit" Version="7.1.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.abstractions" Version="2.0.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>